# Regression Problem on PISA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # this is for visualization
import seaborn as sns # for visualization
%matplotlib inline
import statsmodels.formula.api as sm
import scipy, scipy.stats
import math # log function is inside this library
# this is used to get the plots inline i.e. in the same page
from collections import Counter

In [134]:
df1 = pd.read_csv("pisa2009train.csv")
df2 = pd.read_csv("pisa2009test.csv")

In [3]:
df1.head()

,grade,male,raceeth,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,...,englishAtHome,computerForSchoolwork,read30MinsADay,minutesPerWeekEnglish,studentsInEnglish,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore
0,11,1,NaN,NaN,0.0,NaN,NaN,1.0,NaN,NaN,...,0.0,1.0,0.0,225.0,NaN,1.0,1,1,673.0,476.00
1,11,1,White,0.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,450.0,25.0,1.0,1,0,1173.0,575.01
2,9,1,White,1.0,1.0,1.0,1.0,1.0,1.0,NaN,...,1.0,1.0,0.0,250.0,28.0,1.0,1,0,1233.0,554.81
3,10,0,Black,1.0,1.0,0.0,0.0,1.0,1.0,0.0,...,1.0,1.0,1.0,200.0,23.0,1.0,1,1,2640.0,458.11
4,10,1,Hispanic,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,1.0,1.0,250.0,35.0,1.0,1,1,1095.0,613.89

In [4]:
df2.head()

,grade,male,raceeth,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,...,englishAtHome,computerForSchoolwork,read30MinsADay,minutesPerWeekEnglish,studentsInEnglish,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore
0,10,0,White,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,0.0,240.0,30.0,1.0,1,0,808.0,355.24
1,10,1,White,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,255.0,NaN,1.0,1,0,808.0,385.57
2,10,0,White,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,NaN,30.0,1.0,1,0,808.0,522.62
3,10,0,White,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,0.0,160.0,30.0,NaN,1,0,808.0,406.24
4,10,0,White,1.0,1.0,1.0,0.0,0.0,1.0,1.0,...,1.0,1.0,0.0,240.0,30.0,1.0,1,0,808.0,453.50

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3663 entries, 0 to 3662
Data columns (total 24 columns):
grade                    3663 non-null int64
male                     3663 non-null int64
raceeth                  3628 non-null object
preschool                3607 non-null float64
expectBachelors          3601 non-null float64
motherHS                 3566 non-null float64
motherBachelors          3266 non-null float64
motherWork               3570 non-null float64
fatherHS                 3418 non-null float64
fatherBachelors          3094 non-null float64
fatherWork               3430 non-null float64
selfBornUS               3594 non-null float64
motherBornUS             3592 non-null float64
fatherBornUS             3550 non-null float64
englishAtHome            3592 non-null float64
computerForSchoolwork    3598 non-null float64
read30MinsADay           3629 non-null float64
minutesPerWeekEnglish    3477 non-null float64
studentsInEnglish        3414 non-null float64
schoolHasLibrary         3520 non-null float64
publicSchool             3663 non-null int64
urban                    3663 non-null int64
schoolSize               3501 non-null float64
readingScore             3663 non-null float64
dtypes: float64(19), int64(4), object(1)
memory usage: 686.9+ KB

Ques1. Load the training and testing sets using the read_csv() function, and save them as dataframes with the names pisaTrain and pisaTest. 
How many students are there in the training set?

Ans. Total Number of students in the training set are 3663.

Ques2. Using Group by on pisaTrain, what is the average reading test score of males?
Of Females?

Ans. First Count the No. Males and Females

In [6]:
df1['male'].value_counts()

1    1872
0    1791
Name: male, dtype: int64

The Number of Males are 1872 while Number of Females are 1791

In [7]:
df1.groupby('male')['readingScore'].agg([np.mean])

            mean
male
0     512.940631
1     483.532479

Average reading test score of males is 483.53 while Average reading test score of Female is 512.94

Ques3. Which variables have missing data in at least one observation in the training set?

In [9]:
df1.isnull().sum()

grade                      0
male                       0
raceeth                   35
preschool                 56
expectBachelors           62
motherHS                  97
motherBachelors          397
motherWork                93
fatherHS                 245
fatherBachelors          569
fatherWork               233
selfBornUS                69
motherBornUS              71
fatherBornUS             113
englishAtHome             71
computerForSchoolwork     65
read30MinsADay            34
minutesPerWeekEnglish    186
studentsInEnglish        249
schoolHasLibrary         143
publicSchool               0
urban                      0
schoolSize               162
readingScore               0
dtype: int64

Ans. The coulmns with missing value in the traing set are raceteeth, preschool, expectBachelors,motherHS, motherBachelors, motherWork,fatherHS, fatherBachelors, fatherWork, selfBornUS, motherBornUS, englishAtHome, computerForSchoolWork, read30MinsADay, minutesPerWeekEnglish,studentsInEnglish,schoolHasLibrary & schoolSize.

Ques 4. Linear regression discards observations with missing data, so we will remove all such observations from the training and testing sets. Ideally we should be filling the missing values with plausible information, but for now, lets remove them and move ahead. How many observations are now in the training set? How many observations are now in the testing set?

In [14]:
df1 = df1.dropna(axis=0)

In [16]:
df2.head()

,grade,male,raceeth,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,...,englishAtHome,computerForSchoolwork,read30MinsADay,minutesPerWeekEnglish,studentsInEnglish,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore
0,10,0,White,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,0.0,240.0,30.0,1.0,1,0,808.0,355.24
1,10,1,White,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,255.0,NaN,1.0,1,0,808.0,385.57
2,10,0,White,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,NaN,30.0,1.0,1,0,808.0,522.62
3,10,0,White,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,0.0,160.0,30.0,NaN,1,0,808.0,406.24
4,10,0,White,1.0,1.0,1.0,0.0,0.0,1.0,1.0,...,1.0,1.0,0.0,240.0,30.0,1.0,1,0,808.0,453.50

In [17]:
df2 = df2.dropna(axis=0)

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2414 entries, 1 to 3662
Data columns (total 24 columns):
grade                    2414 non-null int64
male                     2414 non-null int64
raceeth                  2414 non-null object
preschool                2414 non-null float64
expectBachelors          2414 non-null float64
motherHS                 2414 non-null float64
motherBachelors          2414 non-null float64
motherWork               2414 non-null float64
fatherHS                 2414 non-null float64
fatherBachelors          2414 non-null float64
fatherWork               2414 non-null float64
selfBornUS               2414 non-null float64
motherBornUS             2414 non-null float64
fatherBornUS             2414 non-null float64
englishAtHome            2414 non-null float64
computerForSchoolwork    2414 non-null float64
read30MinsADay           2414 non-null float64
minutesPerWeekEnglish    2414 non-null float64
studentsInEnglish        2414 non-null float64
schoolHasLibrary         2414 non-null float64
publicSchool             2414 non-null int64
urban                    2414 non-null int64
schoolSize               2414 non-null float64
readingScore             2414 non-null float64
dtypes: float64(19), int64(4), object(1)
memory usage: 471.5+ KB

In [19]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 990 entries, 0 to 1569
Data columns (total 24 columns):
grade                    990 non-null int64
male                     990 non-null int64
raceeth                  990 non-null object
preschool                990 non-null float64
expectBachelors          990 non-null float64
motherHS                 990 non-null float64
motherBachelors          990 non-null float64
motherWork               990 non-null float64
fatherHS                 990 non-null float64
fatherBachelors          990 non-null float64
fatherWork               990 non-null float64
selfBornUS               990 non-null float64
motherBornUS             990 non-null float64
fatherBornUS             990 non-null float64
englishAtHome            990 non-null float64
computerForSchoolwork    990 non-null float64
read30MinsADay           990 non-null float64
minutesPerWeekEnglish    990 non-null float64
studentsInEnglish        990 non-null float64
schoolHasLibrary         990 non-null float64
publicSchool             990 non-null int64
urban                    990 non-null int64
schoolSize               990 non-null float64
readingScore             990 non-null float64
dtypes: float64(19), int64(4), object(1)
memory usage: 193.4+ KB

Ans. The Number of observations in the training set are 2414 and The Number of observations in testing set are 990

Ques5.	Which of the following variables is an unordered factor/categorical variable with at least 3 levels?

In [20]:
df1['raceeth'].value_counts()

White                                     1470
Hispanic                                   500
Black                                      228
Asian                                       95
More than one race                          81
Native Hawaiian/Other Pacific Islander      20
American Indian/Alaska Native               20
Name: raceeth, dtype: int64

In [21]:
df2['raceeth'].value_counts()

White                                     613
Hispanic                                  201
Black                                      79
Asian                                      45
More than one race                         35
American Indian/Alaska Native              11
Native Hawaiian/Other Pacific Islander      6
Name: raceeth, dtype: int64

Ans. Raceeth is the variable which is an unodered factor/categorical variable with at least 3 levels.

Ques6. If we select White as the reference level, which binary variables will be included in the regression model? (Select all that apply.)

Ans. Acc. to the condition if we select White as the reference level, we will include Hispanic, Black, Asian, More than one race, American Indian/Alaska Native, Native Hawaiin/Other Pacific Islander.

Ques7. Consider again adding our unordered Category race to the regression model with reference level "White". 

For a student who is Asian, which binary variables would be set to 0? All remaining variables will be set to 1.

Ans. For a student who is Asian, the binary variable which will be set to 0 are Hispanic, Black, More Than one race, American Indian/Alaska Native, Native Hawaiian/Other Pacific Islander.

Ques8. For a student who is white, which binary variables would be set to 0? All remaining variables will be set to 1.

For a student who is white, the binary variables that would be set to 0 are Hispanic, Black, Asian, More than one race, American Indian/Alska Native, Native Hawaiian/Other Pacific Islander.

Ques9. Because the race variable takes on text values, we will have to create Dummy Variables before we run Modeling on the data. 

Build a linear regression model (call it lmScore) using the training set to predict readingScore using all the remaining variables. (Including the dummies). Remember to omit one of the dummy variable ( the omitted dummy will be the reference) 

What is the Multiple R-squared value of lmScore on the training set?

In [22]:
df1 = pd.get_dummies(df1,drop_first=True)
df1.head()

,grade,male,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,...,publicSchool,urban,schoolSize,readingScore,raceeth_Asian,raceeth_Black,raceeth_Hispanic,raceeth_More than one race,raceeth_Native Hawaiian/Other Pacific Islander,raceeth_White
1,11,1,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1,0,1173.0,575.01,0,0,0,0,0,1
3,10,0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1,1,2640.0,458.11,0,1,0,0,0,0
4,10,1,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1,1,1095.0,613.89,0,0,1,0,0,0
7,10,0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1,0,1913.0,439.36,0,0,0,0,0,1
9,10,1,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,...,1,0,899.0,465.90,0,0,0,1,0,0

In [23]:
df1 = df1.drop(['raceeth_White'], axis=1)

In [24]:
df1.head()

,grade,male,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,...,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore,raceeth_Asian,raceeth_Black,raceeth_Hispanic,raceeth_More than one race,raceeth_Native Hawaiian/Other Pacific Islander
1,11,1,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1,0,1173.0,575.01,0,0,0,0,0
3,10,0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1.0,1,1,2640.0,458.11,0,1,0,0,0
4,10,1,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1.0,1,1,1095.0,613.89,0,0,1,0,0
7,10,0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1,0,1913.0,439.36,0,0,0,0,0
9,10,1,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,...,1.0,1,0,899.0,465.90,0,0,0,1,0

In [25]:
from sklearn.linear_model import LinearRegression

In [30]:
lmScore=LinearRegression()
lmScore.fit(df1.iloc[:,[0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27]],df1['readingScore'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [31]:
lmScore.intercept_

141.8838859613142

In [32]:
lmScore.coef_

array([ 2.95775015e+01, -1.48059544e+01, -4.42852098e+00,  5.54138008e+01,
        1.30911485e+01, -2.44033758e+00,  6.58506638e+00,  1.72113365e+01,
        5.76467329e+00, -4.38745087e+00, -8.26754712e+00,  4.21836521e+00,
        9.27649884e+00,  2.49986142e+01,  3.44407746e+01,  1.24756805e-02,
       -2.57063241e-01,  1.24532903e+01, -1.79175284e+01, -5.35500471e-01,
        6.88673799e-03, -3.44356841e+00, -6.56206658e+01, -3.79858170e+01,
       -1.57138989e+01, -4.59313444e+00])

In [33]:
df1['PredictScore']=lmScore.predict(df1.iloc[:,[0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27]])

In [42]:
TSS = sum((df1['readingScore']-np.mean(df1['readingScore']))**2)
SSE = sum((df1['readingScore']-df1['PredictScore'])**2)

In [43]:
R2= 1-(SSE1/TSS1)
print(R2)

0.3203690464849498

Ans. R2 Value of lmScore on the training Set is 0.32

Ques10. What is the training-set root-mean squared error (RMSE) of lmScore?

In [51]:
n = len(df1['PredictScore'])
rmse = np.linalg.norm( df1['PredictScore']- df1['readingScore']) / np.sqrt(n)
rmse

73.62460832202646

Ques11.	Consider two students A and B. They have all variable values the same, except that student A is in grade 11 and student B is in grade 9. What is the predicted reading score of student A minus the predicted reading score of student B?

In [59]:
df1.groupby('grade')['PredictScore'].agg([np.mean])

             mean
grade
8      396.896354
9      460.143832
10     515.510316
11     548.815913
12     586.705459

Ques12.	What is the meaning of the coefficient associated with variable raceethAsian?

The coefficient associated with the variable raceethAsian is -3.44356841e+00 which is the predicted diff between an Asian Student and American Indian/Alaska Native student

In [54]:
df1.corr()

,grade,male,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,...,publicSchool,urban,schoolSize,readingScore,raceeth_Asian,raceeth_Black,raceeth_Hispanic,raceeth_More than one race,raceeth_Native Hawaiian/Other Pacific Islander,PredictScore
grade,1.000000,-0.094845,0.005577,0.111908,-0.005934,0.029745,0.004686,0.027235,0.056087,0.005860,...,-0.042782,0.081235,0.073231,0.238684,0.073305,-0.034681,0.007479,0.003369,0.030345,0.421695
male,-0.094845,1.000000,0.010825,-0.092480,0.032062,0.082510,-0.013541,0.038401,0.080779,0.042442,...,-0.091134,0.046370,0.011159,-0.128458,-0.011156,-0.051796,0.013041,0.006438,0.036334,-0.226953
preschool,0.005577,0.010825,1.000000,0.084994,0.138932,0.157264,0.076154,0.115349,0.152761,0.071665,...,-0.098916,-0.019779,-0.026637,0.051289,-0.024427,0.025917,-0.116416,-0.009926,0.014897,0.090615
expectBachelors,0.111908,-0.092480,0.084994,1.000000,0.110999,0.158609,0.076516,0.159939,0.201928,0.015387,...,-0.109273,0.021209,0.032910,0.344304,0.050090,0.010589,-0.077393,-0.003578,0.003860,0.608298
motherHS,-0.005934,0.032062,0.138932,0.110999,1.000000,0.246265,0.159008,0.496570,0.226294,0.004374,...,-0.062628,-0.107021,-0.069267,0.138983,-0.077634,0.082171,-0.341638,0.033328,0.001191,0.223917
motherBachelors,0.029745,0.082510,0.157264,0.158609,0.246265,1.000000,0.138744,0.183158,0.551443,0.074994,...,-0.167888,-0.024376,-0.007007,0.226762,-0.011305,-0.035116,-0.199434,-0.006985,-0.012105,0.400631
motherWork,0.004686,-0.013541,0.076154,0.076516,0.159008,0.138744,1.000000,0.109455,0.059682,0.053199,...,-0.039603,-0.008754,-0.049534,0.024461,-0.057459,0.055439,-0.087753,0.007343,-0.028130,0.043217
fatherHS,0.027235,0.038401,0.115349,0.159939,0.496570,0.183158,0.109455,1.000000,0.267060,0.076893,...,-0.072913,-0.084871,-0.076468,0.168827,0.006188,0.050005,-0.348267,0.015257,0.034694,0.298274
fatherBachelors,0.056087,0.080779,0.152761,0.201928,0.226294,0.551443,0.059682,0.267060,1.000000,0.104815,...,-0.179154,-0.018416,0.009340,0.276978,0.035341,-0.081552,-0.221394,-0.030027,-0.009282,0.489351
fatherWork,0.005860,0.042442,0.071665,0.015387,0.004374,0.074994,0.053199,0.076893,0.104815,1.000000,...,-0.027717,-0.029060,-0.012037,0.076238,-0.020837,-0.090718,-0.016186,-0.022504,-0.041023,0.134694
selfBornUS,-0.043887,0.034550,0.091449,-0.016037,0.188746,0.042323,0.058811,0.161481,0.027220,-0.019417,...,-0.047427,-0.113218,-0.118651,0.013443,-0.217420,0.020548,-0.197021,0.029814,0.005159,0.023751
motherBornUS,-0.083493,0.016537,0.104612,-0.008233,0.357459,0.136149,0.096876,0.300871,0.084592,-0.007144,...,0.008154,-0.255964,-0.253763,0.051460,-0.366386,0.079585,-0.484319,0.028305,-0.087508,0.090916
fatherBornUS,-0.082089,0.009372,0.099267,-0.018543,0.337663,0.112014,0.082602,0.333847,0.098401,-0.005855,...,0.023108,-0.281264,-0.262543,0.065034,-0.335330,0.065296,-0.487314,0.063773,-0.052414,0.114899
englishAtHome,-0.029076,-0.006780,0.121029,0.053815,0.387462,0.157266,0.137826,0.343795,0.138923,0.018774,...,-0.049295,-0.203180,-0.211483,0.107747,-0.222466,0.092098,-0.470549,0.068310,0.005225,0.190363
computerForSchoolwork,0.067693,0.000755,0.101659,0.148997,0.164867,0.139925,0.077968,0.167483,0.165888,0.097214,...,-0.074821,0.046548,0.075320,0.181202,0.030855,-0.059748,-0.057870,-0.026093,0.027770,0.320139
read30MinsADay,0.039724,-0.212847,-0.015333,0.127766,0.010927,0.024801,-0.066722,0.020890,0.046179,0.031059,...,0.009889,0.018436,-0.015859,0.238330,0.038765,0.010003,-0.026254,0.032944,-0.010271,0.421069
minutesPerWeekEnglish,0.017256,-0.007576,-0.030281,0.017679,-0.001195,0.019153,0.019266,0.011755,-0.002486,0.007236,...,0.065916,-0.054023,0.004808,0.036466,0.011307,-0.026156,-0.015695,0.010675,-0.002486,0.064426
studentsInEnglish,0.065092,-0.032794,-0.025685,0.037771,-0.035084,-0.044909,-0.035976,-0.023806,-0.033022,-0.005078,...,0.106491,0.154293,0.296303,0.010252,0.089158,-0.022748,0.066081,0.029569,0.032952,0.018113
schoolHasLibrary,-0.034610,0.047661,0.012239,0.030534,0.006724,0.005664,-0.012607,0.024807,0.005419,-0.020324,...,0.075133,-0.134225,0.079555,0.023558,0.021933,-0.004106,-0.010480,0.004352,-0.011748,0.041620
publicSchool,-0.042782,-0.091134,-0.098916,-0.109273,-0.062628,-0.167888,-0.039603,-0.072913,-0.179154,-0.027717,...,1.000000,-0.334510,0.261286,-0.111669,-0.016799,0.065900,0.019394,0.005665,-0.055688,-0.197291
urban,0.081235,0.046370,-0.019779,0.021209,-0.107021,-0.024376,-0.008754,-0.084871,-0.018416,-0.029060,...,-0.334510,1.000000,0.317388,-0.016017,0.113104,0.074421,0.256300,-0.030588,0.026065,-0.028298
schoolSize,0.073231,0.011159,-0.026637,0.032910,-0.069267,-0.007007,-0.049534,-0.076468,0.009340,-0.012037,...,0.261286,0.317388,1.000000,0.020509,0.080260,0.012752,0.250576,-0.015688,0.009468,0.036235
readingScore,0.238684,-0.128458,0.051289,0.344304,0.138983,0.226762,0.024461,0.168827,0.276978,0.076238,...,-0.111669,-0.016017,0.020509,1.000000,0.070693,-0.200142,-0.191268,-0.001640,0.017141,0.566012
raceeth_Asian,0.073305,-0.011156,-0.024427,0.050090,-0.077634,-0.011305,-0.057459,0.006188,0.035341,-0.020837,...,-0.016799,0.113104,0.080260,0.070693,1.000000,-0.065366,-0.103449,-0.037713,-0.018500,0.124897
raceeth_Black,-0.034681,-0.051796,0.025917,0.010589,0.082171,-0.035116,0.055439,0.050005,-0.081552,-0.090718,...,0.065900,0.074421,0.012752,-0.200142,-0.065366,1.000000,-0.165066,-0.060177,-0.029519,-0.353601
raceeth_Hispanic,0.007479,0.013041,-0.116416,-0.077393,-0.341638,-0.199434,-0.087753,-0.348267,-0.221394,-0.016186,...,0.019394,0.256300,0.250576,-0.191268,-0.103449,-0.165066,1.000000,-0.095236,-0.046716,-0.337923
raceeth_More than one race,0.003369,0.006438,-0.009926,-0.003578,0.033328,-0.006985,0.007343,0.015257,-0.030027,-0.022504,...,0.005665,-0.030588,-0.015688,-0.001640,-0.037713,-0.060177,-0.095236,1.000000,-0.017031,-0.002898
raceeth_Native Hawaiian/Other Pacific Islander,0.030345,0.036334,0.014897,0.003860,0.001191,-0.012105,-0.028130,0.034694,-0.009282,-0.041023,...,-0.055688,0.026065,0.009468,0.017141,-0.018500,-0.029519,-0.046716,-0.017031,1.000000,0.030284
PredictScore,0.421695,-0.226953,0.090615,0.608298,0.223917,0.400631,0.043217,0.298274,0.489351,0.134694,...,-0.197291,-0.028298,0.036235,0.566012,0.124897,-0.353601,-0.337923,-0.002898,0.030284,1.000000

Ques13.	Based on the significance codes, which variables out of these are candidates for removal from the model? Select all that apply. (The factor variable raceeth should only be removed if none of its levels are significant.)

Ans. The raceeth should be removed because some of the variables has low value of the correlation with the reading scores.

Ques14. Using the "predict" function , use the lmScore model to predict the reading scores of students in pisaTest. Call this list of predictions "predTest". Do not change the variables in the model (for example, do not remove variables that we found were not significant in the previous part of this problem). 

What is the range between the maximum and minimum predicted reading score on the test set?

In [135]:
df2 = df2.dropna(axis=0)

In [136]:
df2 = pd.get_dummies(df2,drop_first=True)
df2.head()

,grade,male,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,...,publicSchool,urban,schoolSize,readingScore,raceeth_Asian,raceeth_Black,raceeth_Hispanic,raceeth_More than one race,raceeth_Native Hawaiian/Other Pacific Islander,raceeth_White
0,10,0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,...,1,0,808.0,355.24,0,0,0,0,0,1
4,10,0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1,0,808.0,453.50,0,0,0,0,0,1
6,10,0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1,0,808.0,405.13,0,0,0,0,0,0
7,10,0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,1,0,808.0,665.05,0,0,0,0,0,1
8,11,0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,0,808.0,604.84,0,0,0,0,0,1

In [137]:
df2 = df2.drop(['raceeth_White'], axis=1)

In [138]:
df2.head()

,grade,male,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,...,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore,raceeth_Asian,raceeth_Black,raceeth_Hispanic,raceeth_More than one race,raceeth_Native Hawaiian/Other Pacific Islander
0,10,0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,...,1.0,1,0,808.0,355.24,0,0,0,0,0
4,10,0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,1,0,808.0,453.50,0,0,0,0,0
6,10,0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1,0,808.0,405.13,0,0,0,0,0
7,10,0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,1.0,1,0,808.0,665.05,0,0,0,0,0
8,11,0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1,0,808.0,604.84,0,0,0,0,0

In [139]:
lmScore2=LinearRegression()
lmScore2.fit(df2.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27]],df2['readingScore'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [140]:
lmScore2.intercept_

2.2737367544323206e-13

In [141]:
lmScore2.coef_

array([-1.89302394e-14, -1.50102153e-13,  1.14973451e-13,  8.34356731e-14,
        2.54496760e-14,  5.89356731e-15, -6.57637190e-15, -1.56004049e-14,
        5.22936050e-15,  7.05187072e-15,  3.35787766e-14, -5.18808498e-14,
        1.84388753e-15,  5.56358605e-15, -3.43273490e-15,  1.44605522e-14,
        5.42308320e-16,  8.67578578e-16, -6.77941539e-14, -3.83612277e-14,
       -1.19314579e-13,  5.55111512e-17,  1.00000000e+00,  1.90568861e-16,
       -4.36541807e-15, -1.00070099e-14, -5.78278287e-15])

In [142]:
df2['PredictScore1']=lmScore2.predict(df2.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27]])

In [143]:
df2['PredictScore1'].max()-df2['PredictScore1'].min()

529.8200000000002

Ques15.What is the sum of squared errors (SSE) of lmScore on the testing set? 
_____ (give a integer)

In [145]:
SSE = sum((df2['readingScore']-df2['PredictScore1'])**2)
SSE

2.14889244679059e-23